"""Reproducible benchmark protocols for OmniEvolve research."""

from omnievolve.research.matrix import (
    PILOT_TASK_NAMES,
    PILOT_TASKS,
    AblationVariant,
    BenchmarkJob,
    BenchmarkTask,
    build_context_matrix,
    build_default_matrix,
    build_evaluator_matrix,
    build_operator_portfolio_matrix,
    build_pilot_matrix,
    build_qd_archive_matrix,
    build_reference_credit_matrix,
    build_selector_matrix,
    build_slow_loop_matrix,
    enqueue_matrix,
    load_calibration_repetitions,
    summarize_results,
)
from omnievolve.research.statistics import (
    assess_pilot_gate,
    calibrate_evaluator_noise,
    cliffs_delta,
    holm_adjust,
    paired_randomization_p_value,
    paired_seed_power_analysis,
)
from omnievolve.research.verifier_replay import (
    LabeledPair,
    R1Gate,
    VariantReport,
    VerifierReplayRunner,
    VerifierVariant,
    assess_r1_gate,
    write_report,
)

__all__ = [
    "AblationVariant",
    "BenchmarkJob",
    "BenchmarkTask",
    "PILOT_TASK_NAMES",
    "PILOT_TASKS",
    "build_context_matrix",
    "build_default_matrix",
    "build_evaluator_matrix",
    "build_operator_portfolio_matrix",
    "build_pilot_matrix",
    "build_qd_archive_matrix",
    "build_reference_credit_matrix",
    "build_selector_matrix",
    "build_slow_loop_matrix",
    "assess_pilot_gate",
    "calibrate_evaluator_noise",
    "cliffs_delta",
    "enqueue_matrix",
    "load_calibration_repetitions",
    "holm_adjust",
    "paired_randomization_p_value",
    "paired_seed_power_analysis",
    "summarize_results",
    "LabeledPair",
    "R1Gate",
    "VariantReport",
    "VerifierReplayRunner",
    "VerifierVariant",
    "assess_r1_gate",
    "write_report",
]
